# Generated by Django 5.2.4 on 2025-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_community_image_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(default='communities/default.jpg', upload_to='communities/'),
        ),
    ]
