# Generated by Django 5.2.4 on 2025-09-08 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_community_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
